<a href="https://colab.research.google.com/github/priyansh4320/sns_model_api/blob/main/SNS_MODEL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semantic Similarity Classification Model

In [ ]:
#installing necessary lib
!pip install transformers
!pip install sentence-transformers

In [ ]:
!pip install torch torchvision -U

In [ ]:
#checking if torch is present
import torch

print(torch.__version__)

2.0.1+cu118


In [ ]:
#import necessary lib
from sentence_transformers import SentenceTransformer, util
import numpy as np
from functools import cache

In [ ]:
# load pretrained model stsb-roberta-large
# will be used to extract embeddings and Similarity score from text
model = SentenceTransformer('stsb-roberta-base')

In [ ]:
import pickle
pickle.dump(model,open("transform.pkl",'wb'))

In [ ]:
#testing the pretrained model
sentence1 = "I like Python because I can build AI applications"
sentence2 = "I like Python because I can do data analytics"
# encode sentences to get their embeddings
embedding1 = model.encode(sentence1, convert_to_tensor=True)
embedding2 = model.encode(sentence2, convert_to_tensor=True)
# compute similarity scores of two embeddings
cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)
print("Sentence 1:", sentence1)
print("Sentence 2:", sentence2)
print("Similarity score:", cosine_scores.item())

Sentence 1: I like Python because I can build AI applications
Sentence 2: I like Python because I can do data analytics
Similarity score: 0.7670497894287109


In [ ]:
e = model.encode(df['text1'][0:5],convert_to_tensor=True)

In [ ]:
#import dataset
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Precily AI/Precily_Text_Similarity.csv")
df.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  
0  gardener wins double in glasgow britain s jaso...  
1  amnesty chief laments war failure the lack of ...  
2  hanks greeted at wintry premiere hollywood sta...  
3  redford s vision of sundance despite sporting ...  
4  mauresmo opens with victory in la amelie maure...

In [ ]:
#function for computing similarity score for each pair of text
@cache
def compute_similarity_score(dataframe , len_of_dataframe):
  # encode sentences to get their embeddings
  embedding1 = model.encode(sentence1, convert_to_tensor=True)
  embedding2 = model.encode(sentence2, convert_to_tensor=True)
# compute similarity scores of two embeddings
  cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)
  return cosine_scores.item()

score = compute_similarity_score(sentence1,sentence2)
score

[0.25230738520622253,
 0.2531975209712982,
 0.1261926293373108,
 0.34469395875930786,
 0.38908863067626953,
 0.1271783858537674,
 0.11437475681304932,
 0.2231573760509491,
 0.1401197612285614,
 0.2657514214515686]

In [ ]:
#compute similarity score for every pair
similarity_scores = []
for i in range(len(df)):
  similarity_scores.append(compute_similarity_score(df['text1'][i],df['text2'][i]))

similarity_score[:10]

[0.25230738520622253,
 0.2531975209712982,
 0.1261926293373108,
 0.34469395875930786,
 0.38908863067626953,
 0.1271783858537674,
 0.11437475681304932,
 0.2231573760509491,
 0.1401197612285614,
 0.2657514214515686]

In [ ]:
len(similarity_scores)

3000

In [ ]:
#Generating labels for training 1: similar , 0: not similar
result = []
for i in similarity_scores:
  if i>0.5:
    result.append(1)
  else:
    result.append(0)

In [ ]:
len(result)

list

In [ ]:
#append result and similarity to dataset
df['similarity'] = similarity_scores
df['result']     = result
df.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  similarity  result  
0  gardener wins double in glasgow britain s jaso...    0.252307       0  
1  amnesty chief laments war failure the lack of ...    0.253198       0  
2  hanks greeted at wintry premiere hollywood sta...    0.126193       0  
3  redford s vision of sundance despite sporting ...    0.344694       0  
4  mauresmo opens with victory in la amelie maure...    0.389089       0

In [ ]:
#save progress
df.to_csv("text_similarity2.csv")

In [ ]:
#load progess
df = pd.read_csv("/content/drive/MyDrive/Precily AI/text_similarity2.csv")
df= df[['text1','text2','similarity','result']]
df.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  similarity  result  
0  gardener wins double in glasgow britain s jaso...    0.252307       0  
1  amnesty chief laments war failure the lack of ...    0.253198       0  
2  hanks greeted at wintry premiere hollywood sta...    0.126193       0  
3  redford s vision of sundance despite sporting ...    0.344694       0  
4  mauresmo opens with victory in la amelie maure...    0.389089       0

In [ ]:
#now extract embeddings
text1_embedding, text2_embedding = [],[]
df_len = len(df)

In [ ]:

embedding1 = model.encode(df['text1'][:], convert_to_tensor=True)
embedding2 = model.encode(df['text2'][:], convert_to_tensor=True)


In [ ]:
embedding1[:5]

tensor([[-0.3998, -0.0867, -0.0518,  ..., -0.4862,  0.6913,  1.1125],
        [-0.1120,  0.2030,  0.5536,  ..., -0.8615,  0.4568,  0.3275],
        [-0.4884,  0.2419,  0.0756,  ...,  0.0315, -0.3837,  0.5713],
        [ 0.0187, -0.0910, -0.3588,  ...,  0.0768, -0.2109,  0.8541],
        [-0.2157, -0.0074, -0.3280,  ..., -1.3348, -0.0957,  1.0261]],
       device='cuda:0')

In [ ]:
#now concatinate embedding1 and embedding2 for training as X numpy array
embedding1_cpu = embedding1.cpu().numpy()
embedding2_cpu = embedding2.cpu().numpy()

X = np.concatenate([embedding1_cpu, embedding2_cpu], axis=1)
X[:5]

array([[-0.39975506, -0.08670305, -0.05175658, ..., -0.7451174 ,
        -0.42665374,  0.92428696],
       [-0.11202765,  0.20297253,  0.55359757, ..., -0.47850004,
         0.07787918,  0.5828366 ],
       [-0.4884466 ,  0.24185364,  0.07560961, ..., -0.78080845,
        -0.2231423 ,  1.3101026 ],
       [ 0.01865377, -0.09104314, -0.35878354, ..., -1.332443  ,
         0.21714692,  0.7570285 ],
       [-0.21569566, -0.00740728, -0.32799223, ..., -0.2761358 ,
        -0.31377947,  0.8006909 ]], dtype=float32)

In [ ]:
# target variable
Y = np.asarray(df['similarity'])
Y[:5]

array([0.25230739, 0.25319752, 0.12619263, 0.34469396, 0.38908863])

In [ ]:
#import tensorflow lib for modelling
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
#from tensorflow.keras.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split


In [ ]:
#splitting the dataset
trainx , testx, trainy, testy = train_test_split(X,Y,test_size=0.2);

In [ ]:
#calculating max_length of sequences in to pass it as parameter in Dense layer: input_dim
seq_len = [len(i) for i in X ]
max_sequence_length = max(seq_len)

In [ ]:

#tensorflow regression model: train-test
mod = Sequential()
mod.add(Dense(64, input_dim= max_sequence_length, activation = 'relu' ))
mod.add(Dense(32,activation='relu'))
mod.add(Dense(1))
mod.compile(loss='mse',metrics = [tf.keras.metrics.MeanAbsolutePercentageError()], optimizer='adam')
mod.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                98368     
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 100,481
Trainable params: 100,481
Non-trainable params: 0
_________________________________________________________________


In [ ]:
mod.fit(trainx,trainy, epochs = 10)

Epoch 1/10
75/75 [==============================] - 3s 4ms/step - loss: 0.0488 - mean_absolute_percentage_error: 89.9335
Epoch 2/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0135 - mean_absolute_percentage_error: 61.9730
Epoch 3/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0107 - mean_absolute_percentage_error: 55.6730
Epoch 4/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0086 - mean_absolute_percentage_error: 49.7584
Epoch 5/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0073 - mean_absolute_percentage_error: 46.7657
Epoch 6/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0061 - mean_absolute_percentage_error: 39.9248
Epoch 7/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0053 - mean_absolute_percentage_error: 38.6160
Epoch 8/10
75/75 [==============================] - 0s 4ms/step - loss: 0.0046 - mean_absolute_percentage_error: 35.2561
Epoch 9/10
75/75 [==============

In [ ]:
#predict test set
pred2 = mod.predict(testx)
for i in range(20):
  tf.print(pred2[i])

19/19 [==============================] - 0s 2ms/step
array([0.25011295], dtype=float32)
array([0.4475295], dtype=float32)
array([0.24312735], dtype=float32)
array([0.37268588], dtype=float32)
array([0.31107035], dtype=float32)
array([0.24406105], dtype=float32)
array([0.32220215], dtype=float32)
array([0.37202188], dtype=float32)
array([0.32823327], dtype=float32)
array([0.20149717], dtype=float32)
array([0.41903892], dtype=float32)
array([0.26758233], dtype=float32)
array([0.28666005], dtype=float32)
array([0.19208658], dtype=float32)
array([0.28713503], dtype=float32)
array([0.27891192], dtype=float32)
array([0.21974897], dtype=float32)
array([0.3085504], dtype=float32)
array([0.2655147], dtype=float32)
array([0.22891513], dtype=float32)


In [ ]:
testy[:20]

array([0.02313975, 0.15104368, 0.33001694, 0.35920197, 0.36670446,
       0.19866933, 0.22191724, 0.12838058, 0.21490532, 0.27262998,
       0.18901023, 0.18475741, 0.23359647, 0.29033178, 0.37201431,
       0.26063082, 0.11549377, 0.11153575, 0.29116577, 0.19435184])

In [ ]:
#evaluate model
mod.evaluate(testx,testy)
#eval shows mse as large but if i extract labels 1(similar) and  0(not similar) we get:

19/19 [==============================] - 0s 2ms/step - loss: 0.0205 - mean_absolute_percentage_error: 190.4341


[0.020506802946329117, 190.4341278076172]

In [ ]:
pred_label,test_label = [] ,[]
for i in range(20):
  if pred2[i]>.5:
    pred_label.append(1)
  else:
    pred_label.append(0)

  if testy[i]>.5:
    test_label.append(1)
  else:
    test_label.append(0)

print(pred_label,test_label)

#as you can see after extracting labels we have highly accurate regression model

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
#tensorflow regression model all data
model = Sequential()
model.add(Dense(64, input_dim= max_sequence_length, activation = 'relu' ))
model.add(Dense(32, activation = 'relu' ))
model.add(Dense(1))

model.compile(loss='mse',metrics = [tf.keras.metrics.MeanAbsolutePercentageError()], optimizer='adam')
model.summary()
model.fit(X,Y, epochs=20)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                98368     
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 100,481
Trainable params: 100,481
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
94/94 [==============================] - 2s 3ms/step - loss: 0.0463 - mean_absolute_percentage_error: 117.5741
Epoch 2/20
94/94 [==============================] - 0s 3ms/step - loss: 0.0137 - mean_absolute_percentage_error: 89.5695
Epoch 3/20
94/94 [==============================] - 0s 3ms/step - los

In [ ]:
pickle.dump(mod,open("sns_mod_complete.pkl",'wb'))

In [ ]:
mod.save("precily_sns_mod_complete_regression")

In [ ]:
#saving the model
import shutil
from google.colab import files


folder_name = 'precily_sns_mod_complete_regression_updated2'


shutil.make_archive(folder_name, 'zip', folder_name)


files.download(f'{folder_name}.zip')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import tensorflow as tf
from tensorflow.keras.optimizers import Adam

sns = tf.keras.models.load_model("/content/drive/MyDrive/Precily AI/precily_sns_mod_complete_regression")
#optimizer = Adam(learning_rate=0.001, weight_decay=0.001)
sns.compile(optimizer='rmsprop', loss='mse')


In [ ]:
sns.save("precily_sns_mod_complete_regression_updated2")

In [ ]:
predsns =sns.predict(testx)
predsns[:10]

19/19 [==============================] - 0s 2ms/step


array([[0.4489211 ],
       [0.33822545],
       [0.20955962],
       [0.27417386],
       [0.3727121 ],
       [0.2890916 ],
       [0.37334803],
       [0.23771752],
       [0.20129272],
       [0.3306707 ]], dtype=float32)

In [ ]:
testy[:10]

array([0.40822387, 0.26543796, 0.22970027, 0.21661988, 0.31610751,
       0.21600719, 0.37323391, 0.26371861, 0.25038868, 0.33439362])

In [ ]:
import pickle
model = pickle.load(open('sns_mod_complete.pkl','rb'))